if ( isMultiplayer ) then {
	FCLIB_difficulty_modifier = ["Difficulty",1] call bis_fnc_getParamValue;
	FCLIB_time_factor = ["DayDuration",12] call bis_fnc_getParamValue;
	FCLIB_resources_multiplier = ["ResourcesMultiplier",1] call bis_fnc_getParamValue;
	FCLIB_fatigue = ["Fatigue",1] call bis_fnc_getParamValue;
	FCLIB_introduction = ["Introduction",1] call bis_fnc_getParamValue;
	FCLIB_deployment_cinematic = ["DeploymentCinematic",1] call bis_fnc_getParamValue;
	FCLIB_unitcap = ["Unitcap",1] call bis_fnc_getParamValue;
	FCLIB_adaptive_opfor = ["AdaptToPlayercount",1] call bis_fnc_getParamValue;
	FCLIB_civilian_activity = ["civilians",1] call bis_fnc_getParamValue;
	FCLIB_teamkill_penalty = ["TeamkillPenalty",0] call bis_fnc_getParamValue;
	FCLIB_build_first_fob = ["FirstFob",0] call bis_fnc_getParamValue;
	FCLIB_param_wipe_savegame_1 = ["WipeSave1",0] call bis_fnc_getParamValue;
	FCLIB_param_wipe_savegame_2 = ["WipeSave2",0] call bis_fnc_getParamValue;
	FCLIB_passive_income = ["PassiveIncome",0] call bis_fnc_getParamValue;
	FCLIB_permissions_param = ["Permissions",1] call bis_fnc_getParamValue;
	FCLIB_halo_param = ["HaloJump",1] call bis_fnc_getParamValue;
	FCLIB_use_whitelist = ["Whitelist",0] call bis_fnc_getParamValue;
	FCLIB_cleanup_vehicles = ["CleanupVehicles",2] call bis_fnc_getParamValue;
	FCLIB_csat_aggressivity = ["Aggressivity",1] call bis_fnc_getParamValue;
	FCLIB_weather_param = ["Weather",3] call bis_fnc_getParamValue;
	FCLIB_shorter_nights = ["ShorterNights",0] call bis_fnc_getParamValue;
	FCLIB_ammo_bounties = [ "AmmoBounties",0] call bis_fnc_getParamValue;
	FCLIB_civ_penalties = [ "CivPenalties",0] call bis_fnc_getParamValue;
	FCLIB_remote_sensors = [ "DisableRemoteSensors",0] call bis_fnc_getParamValue;
	FCLIB_blufor_defenders = [ "BluforDefenders",1] call bis_fnc_getParamValue;
	FCLIB_autodanger = [ "Autodanger",0] call bis_fnc_getParamValue;
	FCLIB_maximum_fobs = [ "MaximumFobs",26] call bis_fnc_getParamValue;
	FCLIB_max_squad_size = ["MaxSquadSize",10] call bis_fnc_getParamValue;
} else {
	FCLIB_difficulty_modifier = 1;
	FCLIB_time_factor = 12;
	FCLIB_resources_multiplier = 1;
	FCLIB_fatigue = 1;
	FCLIB_introduction = 0;
	FCLIB_deployment_cinematic = 0;
	FCLIB_adaptive_opfor = 1;
	FCLIB_unitcap = 1;
	FCLIB_civilian_activity = 1;
	FCLIB_teamkill_penalty = 0;
	FCLIB_build_first_fob = 0;
	FCLIB_param_wipe_savegame_1 = 0;
	FCLIB_param_wipe_savegame_2 = 0;
	FCLIB_passive_income = 0;
	FCLIB_permissions_param = 1;
	FCLIB_halo_param = 1;
	FCLIB_use_whitelist = 0;
	FCLIB_cleanup_vehicles = 2;
	FCLIB_csat_aggressivity = 1;
	FCLIB_weather_param = 3;
	FCLIB_shorter_nights = 0;
	FCLIB_ammo_bounties = 1;
	FCLIB_civ_penalties = 1;
	FCLIB_remote_sensors = 0;
	FCLIB_blufor_defenders = 1;
	FCLIB_autodanger = 0;
	FCLIB_maximum_fobs = 26;
	FCLIB_max_squad_size = 10;
};

if ( FCLIB_fatigue < 0.1 ) then { FCLIB_fatigue = false } else { FCLIB_fatigue = true };
if ( FCLIB_introduction == 1 ) then { FCLIB_introduction = true } else { FCLIB_introduction = false };
if ( FCLIB_deployment_cinematic == 1 ) then { FCLIB_deployment_cinematic = true } else { FCLIB_deployment_cinematic = false };
if ( FCLIB_build_first_fob == 1 ) then { FCLIB_build_first_fob = true } else { FCLIB_build_first_fob = false };
if ( FCLIB_teamkill_penalty == 1 ) then { FCLIB_teamkill_penalty = true } else { FCLIB_teamkill_penalty = false };
if ( FCLIB_adaptive_opfor == 1 ) then { FCLIB_adaptive_opfor = true } else { FCLIB_adaptive_opfor = false };
if ( FCLIB_passive_income == 1 ) then { FCLIB_passive_income = true } else { FCLIB_passive_income = false };
if ( FCLIB_permissions_param == 1 ) then { FCLIB_permissions_param = true } else { FCLIB_permissions_param = false };
if ( FCLIB_use_whitelist == 1 ) then { FCLIB_use_whitelist = true } else { FCLIB_use_whitelist = false };
if ( FCLIB_shorter_nights == 1 ) then { FCLIB_shorter_nights = true } else { FCLIB_shorter_nights = false };
if ( FCLIB_ammo_bounties == 1 ) then { FCLIB_ammo_bounties = true } else { FCLIB_ammo_bounties = false };
if ( FCLIB_civ_penalties == 1 ) then { FCLIB_civ_penalties = true } else { FCLIB_civ_penalties = false };
if ( FCLIB_blufor_defenders == 1 ) then { FCLIB_blufor_defenders = true } else { FCLIB_blufor_defenders = false };
if ( FCLIB_autodanger == 1 ) then { FCLIB_autodanger = true } else { FCLIB_autodanger = false };